"use server";

import { redirect } from "next/navigation";
import { adminBaseUrl, isAdminEmail } from "@/lib/admin";
import { adminSignInEmail } from "@/lib/email/templates";
import { emailConfigured, sendEmail } from "@/lib/email/resend";
import { getServerSupabase, hasServiceRole } from "@/lib/supabase/server";

/**
 * Email a one-time sign-in link to an allowed admin. The link is generated by
 * Supabase Auth but delivered through Resend (template in code), so it doesn't
 * depend on Supabase's rate-limited default mailer. The response is the same
 * whether or not the address is allowed, so the form can't be used to probe
 * the admin list.
 */
export async function sendSignInLink(formData: FormData) {
  const email = String(formData.get("email") ?? "").trim().toLowerCase();

  if (isAdminEmail(email)) {
    const supabase = getServerSupabase();
    if (!supabase || !hasServiceRole() || !emailConfigured()) {
      redirect("/admin/login?error=config");
    }

    let link = await supabase.auth.admin.generateLink({ type: "magiclink", email });
    if (link.error) {
      // First sign-in: create the (pre-confirmed) user, then try again.
      await supabase.auth.admin.createUser({ email, email_confirm: true });
      link = await supabase.auth.admin.generateLink({ type: "magiclink", email });
    }
    const tokenHash = link.data.properties?.hashed_token;
    if (link.error || !tokenHash) {
      console.error("admin sign-in link failed", link.error?.message);
      redirect("/admin/login?error=send");
    }

    const url = `${adminBaseUrl()}/admin/auth/confirm?token_hash=${encodeURIComponent(tokenHash)}&type=magiclink`;
    const sent = await sendEmail({ to: email, ...adminSignInEmail(url) });
    if (!sent.ok) {
      console.error("admin sign-in email failed", sent.error);
      redirect("/admin/login?error=send");
    }
  }

  redirect("/admin/login?sent=1");
}
